print("特征验证工具")
print("=" * 80)
print("用法：")
print("  from src.features.validator import validate_features, fix_features")
print("  from src.features.validator import normalize_volume_features")
print("  from src.features.validator import check_feature_distribution, print_feature_stats")
print()
print("  # 验证和修复特征")
print("  is_valid, issues = validate_features(df)")
print("  if not is_valid:")
print("      df = fix_features(df)")
print()
print("  # 标准化成交量特征")
print("  df = normalize_volume_features(df)")
print()
print("  # 检查特征分布")
print("  stats = check_feature_distribution(df, feature_cols)")
print("  print_feature_stats(stats)")
print("=" * 80)